-- MySQL Script generated by MySQL Workbench
-- 08/22/16 22:49:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto` DEFAULT CHARACTER SET utf8 ;
USE `projeto` ;

-- -----------------------------------------------------
-- Table `projeto`.`armazenamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`armazenamento` (
  `idArmazenamento` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `formato` VARCHAR(16) NULL DEFAULT NULL,
  `tipo` VARCHAR(16) NULL DEFAULT NULL,
  `capacidade` VARCHAR(16) NULL DEFAULT NULL,
  `cache` VARCHAR(16) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idArmazenamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto`.`cpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`cpu` (
  `idCpu` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `speed` VARCHAR(16) NULL DEFAULT NULL,
  `socket` VARCHAR(45) NULL,
  `cores` INT(3) NULL DEFAULT NULL,
  `tdp` VARCHAR(16) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idCpu`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto`.`gabinete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`gabinete` (
  `idGabinete` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `classe` VARCHAR(16) NULL,
  `moboPadrao` VARCHAR(16) NULL,
  `slotWater` VARCHAR(45) NULL,
  `acrilico` VARCHAR(16) NULL,
  `conexoes` VARCHAR(16) NULL,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idGabinete`),
  UNIQUE INDEX `idGabinete` (`idGabinete` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto`.`gpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`gpu` (
  `idGpu` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `chipset` VARCHAR(45) NULL DEFAULT NULL,
  `memoria` VARCHAR(16) NULL DEFAULT NULL,
  `clock` VARCHAR(16) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idGpu`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto`.`ram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`ram` (
  `idRam` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `speed` VARCHAR(16) NULL DEFAULT NULL,
  `tipo` VARCHAR(16) NULL DEFAULT NULL,
  `modulos` VARCHAR(16) NULL DEFAULT NULL,
  `tamanho` VARCHAR(16) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idRam`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto`.`motherboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`motherboard` (
  `idMotherboard` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `socket` VARCHAR(16) NULL DEFAULT NULL,
  `formFactor` VARCHAR(16) NULL DEFAULT NULL,
  `ramSlots` INT(3) NULL DEFAULT NULL,
  `maxRam` VARCHAR(16) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idMotherboard`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto`.`psu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`psu` (
  `idPsu` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `potencia` VARCHAR(16) NULL,
  `padrao` VARCHAR(16) NULL,
  `eightyPlus` VARCHAR(16) NULL,
  `modular` VARCHAR(16) NULL,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idPsu`),
  UNIQUE INDEX `idPSU` (`idPsu` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projeto`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario` (`idUsuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
